package setup

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/Kenzi-Siaufandi/tidy/internal/config"
	"github.com/Kenzi-Siaufandi/tidy/internal/resolver"
	"github.com/Kenzi-Siaufandi/tidy/internal/ui"
)

// WizardServer holds the [server] answers.
type WizardServer struct {
	Project string
	Version string
	Build   string
}

// WizardPlugin holds one [plugins.<name>] answer.
type WizardPlugin struct {
	Name        string
	Source      string // "modrinth", "url", or "local"
	ProjectID   string
	Version     string
	GameVersion string
	Loader      string
	Channel     string
	URL         string
	Path        string
	SHA256      string
}

// WizardSpec is the full set of wizard answers.
type WizardSpec struct {
	Server  WizardServer
	Plugins []WizardPlugin
}

func tomlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`)
	return `"` + r.Replace(s) + `"`
}

func tomlKey(s string) string {
	if s == "" {
		return tomlString(s)
	}
	for _, c := range s {
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '_' || c == '-') {
			return tomlString(s)
		}
	}
	return s
}

// BuildTOML renders a WizardSpec as tidy.toml content.
func BuildTOML(spec WizardSpec) string {
	var b strings.Builder
	b.WriteString("# Generated by `tidy setup new`. See tidy.toml.example for full reference.\n\n")
	b.WriteString("[server]\n")
	b.WriteString("project = " + tomlString(spec.Server.Project) + "\n")
	b.WriteString("version = " + tomlString(spec.Server.Version) + "\n")
	build := strings.TrimSpace(spec.Server.Build)
	if build == "" {
		build = "latest"
	}
	b.WriteString("build = " + tomlString(build) + "\n")

	for _, p := range spec.Plugins {
		b.WriteString("\n[plugins." + tomlKey(p.Name) + "]\n")
		if strings.EqualFold(strings.TrimSpace(p.Source), "url") {
			b.WriteString("source = \"url\"\n")
			b.WriteString("url = " + tomlString(p.URL) + "\n")
			b.WriteString("sha256 = " + tomlString(strings.ToLower(strings.TrimSpace(p.SHA256))) + "\n")
			continue
		}
		if strings.EqualFold(strings.TrimSpace(p.Source), "local") {
			b.WriteString("source = \"local\"\n")
			b.WriteString("path = " + tomlString(p.Path) + "\n")
			b.WriteString("sha256 = " + tomlString(strings.ToLower(strings.TrimSpace(p.SHA256))) + "\n")
			continue
		}
		b.WriteString("source = \"modrinth\"\n")
		b.WriteString("project_id = " + tomlString(p.ProjectID) + "\n")
		ver := strings.TrimSpace(p.Version)
		if ver == "" {
			ver = "latest"
		}
		b.WriteString("version = " + tomlString(ver) + "\n")
		if gv := strings.TrimSpace(p.GameVersion); gv != "" {
			b.WriteString("game_version = " + tomlString(gv) + "\n")
		}
		loader := strings.ToLower(strings.TrimSpace(p.Loader))
		if loader == "" {
			loader = config.DefaultModrinthLoader
		}
		channel := strings.ToLower(strings.TrimSpace(p.Channel))
		if channel == "" {
			channel = config.DefaultModrinthChannel
		}
		b.WriteString("loader = " + tomlString(loader) + "\n")
		b.WriteString("channel = " + tomlString(channel) + "\n")
	}
	return b.String()
}

// prompter reads interactive answers with defaults; EOF counts as empty.
type prompter struct {
	r *bufio.Reader
	w io.Writer
}

func (p *prompter) ask(label, def string) string {
	if def != "" {
		fmt.Fprintf(p.w, "%s (default: %s): ", label, def)
	} else {
		fmt.Fprintf(p.w, "%s: ", label)
	}
	line, err := p.r.ReadString('\n')
	if err != nil && len(line) == 0 {
		return def
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

// askRequired prompts once; empty (or EOF) returns "" so the caller can skip.
func (p *prompter) askRequired(label string) string {
	return p.ask(label, "")
}

func isHex64(s string) bool {
	if len(s) != 64 {
		return false
	}
	for _, c := range s {
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f' || c >= 'A' && c <= 'F') {
			return false
		}
	}
	return true
}

// runWizard drives the interactive questionnaire.
func runWizard(p *prompter) WizardSpec {
	var spec WizardSpec

	fmt.Fprintln(p.w, ui.Bold("--- Server ---"))
	project := p.ask("Server project [paper/purpur]", "paper")
	if strings.TrimSpace(project) == "" {
		project = "paper"
	}
	suggestVersion := "26.3"
	if resolver.IsPurpurProject(project) {
		suggestVersion = "1.21.8"
	}
	version := p.ask("Server version", suggestVersion)
	if strings.TrimSpace(version) == "" {
		version = suggestVersion
	}
	build := p.ask("Build [latest or numeric pin]", "latest")
	if strings.TrimSpace(build) == "" {
		build = "latest"
	}
	spec.Server = WizardServer{Project: strings.TrimSpace(project), Version: strings.TrimSpace(version), Build: strings.TrimSpace(build)}

	fmt.Fprintln(p.w, ui.Bold("--- Plugins (Enter skips) ---"))
	for {
		name := p.ask("Add plugin [name, or Enter to finish]", "")
		if name == "" {
			break
		}
		source := strings.ToLower(p.ask(fmt.Sprintf("Source for %q [modrinth/url/local]", name), "modrinth"))
		if source != "url" && source != "modrinth" && source != "local" {
			fmt.Fprintln(p.w, ui.Yellow("[!] Unknown source, using modrinth."))
			source = "modrinth"
		}
		plugin := WizardPlugin{Name: name, Source: source}
		if source == "local" {
			plugin.Path = p.askRequired("Local jar path (e.g. plugins/MyPlugin.jar)")
			if plugin.Path == "" {
				fmt.Fprintln(p.w, ui.Yellow("[!] Skipped: path is required for local plugins."))
				continue
			}
			for {
				sha := p.ask("SHA-256 (64 hex chars)", "")
				if sha == "" {
					fmt.Fprintln(p.w, ui.Yellow("[!] Skipped: sha256 is required for local plugins."))
					plugin.Path = ""
					break
				}
				if isHex64(strings.TrimSpace(sha)) {
					plugin.SHA256 = sha
					break
				}
				fmt.Fprintln(p.w, ui.Yellow("[!] Must be exactly 64 hex characters."))
			}
			if plugin.Path == "" {
				continue
			}
		} else if source == "url" {
			plugin.URL = p.askRequired("Download URL")
			if plugin.URL == "" {
				fmt.Fprintln(p.w, ui.Yellow("[!] Skipped: URL is required."))
				continue
			}
			for {
				sha := p.ask("SHA-256 (64 hex chars)", "")
				if sha == "" {
					fmt.Fprintln(p.w, ui.Yellow("[!] Skipped: sha256 is required for url plugins."))
					plugin.URL = ""
					break
				}
				if isHex64(strings.TrimSpace(sha)) {
					plugin.SHA256 = sha
					break
				}
				fmt.Fprintln(p.w, ui.Yellow("[!] Must be exactly 64 hex characters."))
			}
			if plugin.URL == "" {
				continue
			}
		} else {
			plugin.ProjectID = p.ask("Modrinth project_id", strings.ToLower(name))
			if plugin.ProjectID == "" {
				plugin.ProjectID = strings.ToLower(name)
			}
			plugin.Version = p.ask("Version [latest or pin]", "latest")
			plugin.GameVersion = p.ask("Minecraft game_version [optional]", "")
			plugin.Loader = p.ask("Loader", config.DefaultModrinthLoader)
			for {
				ch := p.ask("Channel [release/beta/alpha]", config.DefaultModrinthChannel)
				if ch == "" {
					ch = config.DefaultModrinthChannel
				}
				if ch == "release" || ch == "beta" || ch == "alpha" {
					plugin.Channel = ch
					break
				}
				fmt.Fprintln(p.w, ui.Yellow("[!] Must be release, beta, or alpha."))
			}
		}
		spec.Plugins = append(spec.Plugins, plugin)
		fmt.Fprintf(p.w, "%s\n", ui.Green(fmt.Sprintf("[+] Added plugin %q (%s).", name, source)))
	}
	return spec
}

// CmdNew runs the tidy.toml creation wizard.
func CmdNew(root, output string, force bool, stdin io.Reader, stdout io.Writer) int {
	if strings.TrimSpace(output) == "" {
		output = "tidy.toml"
	}
	dest := output
	if !filepath.IsAbs(dest) {
		dest = filepath.Join(root, dest)
	}

	if _, err := os.Stat(dest); err == nil && !force {
		fmt.Fprintf(os.Stderr, "%s\n", ui.Red(fmt.Sprintf("[!] %s already exists (use --force to overwrite).", dest)))
		return 1
	}

	if stdin == nil {
		stdin = os.Stdin
	}
	if stdout == nil {
		stdout = os.Stdout
	}
	fmt.Fprintln(stdout, ui.Bold(ui.Cyan("Creating a new tidy.toml (Ctrl+C to abort)...")))
	br := bufio.NewReader(stdin)
	spec := runWizard(&prompter{r: br, w: stdout})

	content := BuildTOML(spec)
	if _, err := config.ParseConfig([]byte(content)); err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", ui.Red(fmt.Sprintf("[!] Generated config is invalid: %v", err)))
		return 1
	}

	if !force {
		confirm := (&prompter{r: br, w: stdout}).ask(fmt.Sprintf("Write to %s?", dest), "Y")
		if !strings.EqualFold(strings.TrimSpace(confirm), "y") && !strings.EqualFold(strings.TrimSpace(confirm), "yes") && strings.TrimSpace(confirm) != "" {
			fmt.Fprintln(stdout, ui.Yellow("Aborted. Nothing written."))
			return 0
		}
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", ui.Red(fmt.Sprintf("[!] Failed to create directory: %v", err)))
		return 1
	}
	if err := os.WriteFile(dest, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", ui.Red(fmt.Sprintf("[!] Failed to write %s: %v", dest, err)))
		return 1
	}
	fmt.Fprintf(stdout, "%s\n", ui.Green(fmt.Sprintf("[+] Wrote %s (%d plugin(s)).", dest, len(spec.Plugins))))
	fmt.Fprintf(stdout, "Next: %s, then run %s\n", ui.Cyan("tidy setup check"), ui.Cyan("tidy"))
	return 0
}
